import Head from "next/head";
import { useSession } from "next-auth/react";
import Chat from "@/components/Chat";
import Auth from "@/components/Auth";

export default function Home() {
  const { data: session } = useSession();
  const reloadSession = () => {
    const event = new Event("visibilitychange");
    document.dispatchEvent(event);
  };
  return (
    <>
      <Head>
        <title>DamarChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        {session?.user?.username ? (
          <Chat session={session} />
        ) : (
          <Auth reloadSession={reloadSession} session={session} />
        )}
      </main>
    </>
  );
}
